// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiAQEDvtyHo-e1c5OGKZvVbC3irk2dtKc',
    appId: '1:564340092882:web:d8d90643c858507de7220b',
    messagingSenderId: '564340092882',
    projectId: 'instaclone-faebb',
    authDomain: 'instaclone-faebb.firebaseapp.com',
    storageBucket: 'instaclone-faebb.appspot.com',
    measurementId: 'G-MHC4R8KZJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJyyMRare0-fakQt2ZFvly0YCVYMer-a4',
    appId: '1:564340092882:android:02959b409e434149e7220b',
    messagingSenderId: '564340092882',
    projectId: 'instaclone-faebb',
    storageBucket: 'instaclone-faebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-l_n0p0Mf9vUj-F5W-1pwtCWbxyROCxE',
    appId: '1:564340092882:ios:8c4d45eaba657398e7220b',
    messagingSenderId: '564340092882',
    projectId: 'instaclone-faebb',
    storageBucket: 'instaclone-faebb.appspot.com',
    iosClientId: '564340092882-gsb4s00j6re8dugf8bc8kbk710lp7u4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-l_n0p0Mf9vUj-F5W-1pwtCWbxyROCxE',
    appId: '1:564340092882:ios:8c4d45eaba657398e7220b',
    messagingSenderId: '564340092882',
    projectId: 'instaclone-faebb',
    storageBucket: 'instaclone-faebb.appspot.com',
    iosClientId: '564340092882-gsb4s00j6re8dugf8bc8kbk710lp7u4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
